### ISSUE TITLE
Memory limit bug multiple views

### ISSUE THREAD

**Issue by rubenteste** [olexale/arkit_flutter_plugin#136]
i'm running arkit on ios, it works, but if i reopen multiple timesthe arkit plugin it crashes because of memory problem
i'm trying to call dispose and/or similar function to end the plugin every time i leave the page but not found a solution:

How fully kill an ARKitSceneView? @olexale  

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=1450 MB, unused=0x0)
    frame #0: 0x00000001db0528e4 libsystem_platform.dylib`__bzero + 68
libsystem_platform.dylib`__bzero:
->  0x1db0528e4 <+68>: dc     zva, x3
    0x1db0528e8 <+72>: add    x3, x3, #0x40             ; =0x40 
    0x1db0528ec <+76>: subs   x2, x2, #0x40             ; =0x40 
    0x1db0528f0 <+80>: b.hi   0x1db0528e4               ; <+68>
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by olexale** [comment]
hi! what plugin version are you using? could you provide some sample code that illustrates the problem?

**Comment by chinmaySciverse** [comment]
The 'arkit_0' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.


* thread #13, name = 'io.worker.1', stop reason = EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=2098 MB)
 frame #0: 0x0000000102e0039c Flutter`neon::store_1010102_xr(unsigned long, SkRasterPipelineStage*, unsigned long, unsigned long, std::byte*, float vector[4], float vector[4], float vector[4], float vector[4], float vector[4], float vector[4], float vector[4], float vector[4]) + 188
Flutter`neon::store_1010102_xr:
-> 0x102e0039c <+188>: str q16, [x8]
 0x102e003a0 <+192>: ldr x5, [x1, #0x10]!
 0x102e003a4 <+196>: br x5
 0x102e003a8 <+200>: cmp x0, #0x1
Target 0: (Runner) stopped.
Lost connection to device.


what could be a possible reason for this error

@olexale

**Comment by olexale** [comment]
Should we fixed in `1.0.7`.

**Comment by chinmaySciverse** [comment]
Thanks a lot !
