### ISSUE TITLE
Remote Object

### ISSUE THREAD

**Issue by stevedj** [olexale/arkit_flutter_plugin#62]
Hi Oleksandr Leuschenko,

Once again, thank you very much for your amazing plugin!
I would like to ask about the remote object capability,
is it possible to use a downloaded .dae file?
or maybe a downloaded .dae file saved in the local directory?

Best Regards
Steve

**Comment by olexale** [comment]
Hi @stevedj ,

Thanks! There is a [pull request](https://github.com/olexale/arkit_flutter_plugin/pull/61) which does exactly that. I hope @miles-au will be able to change it a bit so we'll merge it in the master branch. Otherwise, I'll implement these changes when I have some time.

Kind regards,
Oleksandr

**Comment by stevedj** [comment]
Thank you so Much @olexale,

I will try to look at it, and help if I can

Warmest regards,
Steve
